"""Markdown for the two things this repo produces: findings and new monsters.

Every report states the combat profile it was solved under. That is not
decoration - a loadout is only best-in-slot relative to a set of prayers and
potions, and the same fight ranks its weapons differently without them.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from engine import describe_profile  # noqa: E402

DISCLAIMER = [
    "Generated by osrs-meta-lab. DPS from the OSRS Wiki's calculator, used",
    "unmodified. Raw DPS only: it ignores cost, obtainability, supplies and",
    "fight mechanics such as phases, movement and downtime. A starting point",
    "for investigation, not a recommendation.",
]

# What the calculator said it could not model. Reproduced in full rather than
# summarised, because a number carrying one of these is not the same claim as
# a number without.
WARNING_TEXT = {
    "equipment_slot_body_unsupported_set_effect":
        "the calculator does not model this loadout's armour set effect",
    "pvm_results_weapon_unsupported_spec":
        "this weapon's special attack is not modelled",
    "monster_overall_unique_effects":
        "this monster has unique mechanics the calculator does not model",
    "equipment_slot_hands_effect":
        "this glove's effect is not modelled",
}


def gear_lines(result) -> list[str]:
    out = [f"- **weapon**: {result.weapon}"]
    if result.ammo:
        out.append(f"- **ammo**: {result.ammo}")
    if result.spell:
        out.append(f"- **spell**: {result.spell}")
    for slot, item in sorted(result.gear.items()):
        out.append(f"- **{slot}**: {item}")
    return out


def warning_lines(warnings: list[str]) -> list[str]:
    if not warnings:
        return []
    out = ["", "> **Treat with caution.** The calculator flagged this loadout:"]
    for w in warnings:
        out.append(f"> - {WARNING_TEXT.get(w, w)}")
    return out


def finding(row: dict) -> str:
    """A same-tier improvement over the published setup."""
    base, con, unc = row["baseline"], row["constrained"], row["unconstrained"]
    lines = [
        f"# {row['label']}",
        "",
        f"The published **{base['variant']}** setup scores **{base['dps']:.3f} dps**.",
        f"Drawn from the same items the wiki's own setups for this activity name,",
        f"the solver reaches **{con['dps']:.3f} dps** - a **{con['delta']:+.1%}** difference.",
        "",
        f"Solved under **{con['profile']}**.",
        "",
        "## Why this is not just better gear",
        "",
        "The comparison is restricted to equipment the published setups already",
        "use, so this is the same gear arranged differently rather than a richer",
        "player beating a budget guide. For reference, unconstrained",
        f"best-in-slot from the whole game reaches {unc['dps']:.3f} dps",
        f"({unc['delta']:+.1%}), which is the tier gap and is *not* the finding.",
        "",
        "## Loadout",
        "",
        f"- **style**: {con['styleName']} ({con['style']})",
    ]
    lines += [f"- **{k}**: {v}" for k, v in (
        ("weapon", con["weapon"]), ("ammo", con["ammo"]), ("spell", con["spell"]),
    ) if v]
    lines += [f"- **{slot}**: {item}" for slot, item in sorted(con["gear"].items())]
    lines += warning_lines(con["warnings"] + base["warnings"])
    lines += ["", "---", ""] + DISCLAIMER
    return "\n".join(lines) + "\n"


def new_monster(monster: dict, style: str, ranked: list) -> str:
    d = monster.get("defensive", {})
    s = monster.get("skills", {})
    lines = [
        f"# {monster.get('name')} {monster.get('version') or ''}".strip(),
        "",
        "**Newly detected monster.** Release-day stats on the wiki are often",
        "provisional - re-run once they settle.",
        "",
        "## Stats",
        "",
        f"- Hitpoints **{s.get('hp')}**, defence level **{s.get('def')}**",
        f"- Defence: stab {d.get('stab')} / slash {d.get('slash')} / crush {d.get('crush')}"
        f" / magic {d.get('magic')} / ranged {d.get('standard')}",
        f"- Size {monster.get('size')}, attack speed {monster.get('speed')}",
    ]
    weakness = monster.get("weakness")
    if weakness:
        lines.append(f"- Elemental weakness: **{weakness.get('element')}** "
                     f"({weakness.get('severity')}%)")
    attrs = monster.get("attributes") or []
    if attrs:
        lines.append(f"- Attributes: {', '.join(attrs)}")

    lines += ["", f"## Best {style}", "",
              f"Solved under **{describe_profile(style)}**.", "",
              "| DPS | Weapon | Style | Max hit |", "|---|---|---|---|"]
    for r in ranked[:5]:
        lines.append(f"| {r.dps:.3f} | {r.weapon} | {r.style_name} | {r.max_hit} |")
    lines += ["", "Gear for the top result:", ""] + gear_lines(ranked[0])
    lines += warning_lines(ranked[0].warnings)
    lines += ["", "---", ""] + DISCLAIMER
    return "\n".join(lines) + "\n"


def slug(name: str) -> str:
    out = "".join(c.lower() if c.isalnum() else "-" for c in name)
    return "-".join(p for p in out.split("-") if p) or "unnamed"
